/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_CLAVES_H_RPCGEN
#define _RPC_CLAVES_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct tuple_t {
	int key;
	char *value1;
	int N_value2;
	struct {
		u_int V_value2_len;
		double *V_value2_val;
	} V_value2;
};
typedef struct tuple_t tuple_t;

struct returnGetValue {
	int result;
	tuple_t tuple_result;
};
typedef struct returnGetValue returnGetValue;

#define CLAVE_PROG 1
#define CLAVE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define INIT 1
extern  enum clnt_stat init_1(int *, CLIENT *);
extern  bool_t init_1_svc(int *, struct svc_req *);
#define SET_VALUE 2
extern  enum clnt_stat set_value_1(tuple_t , int *, CLIENT *);
extern  bool_t set_value_1_svc(tuple_t , int *, struct svc_req *);
#define GET_VALUE 3
extern  enum clnt_stat get_value_1(int , returnGetValue *, CLIENT *);
extern  bool_t get_value_1_svc(int , returnGetValue *, struct svc_req *);
#define MODIFY_VALUE 4
extern  enum clnt_stat modify_value_1(tuple_t , int *, CLIENT *);
extern  bool_t modify_value_1_svc(tuple_t , int *, struct svc_req *);
#define DELETE_KEY 5
extern  enum clnt_stat delete_key_1(int , int *, CLIENT *);
extern  bool_t delete_key_1_svc(int , int *, struct svc_req *);
#define EXIST 6
extern  enum clnt_stat exist_1(int , int *, CLIENT *);
extern  bool_t exist_1_svc(int , int *, struct svc_req *);
extern int clave_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define INIT 1
extern  enum clnt_stat init_1();
extern  bool_t init_1_svc();
#define SET_VALUE 2
extern  enum clnt_stat set_value_1();
extern  bool_t set_value_1_svc();
#define GET_VALUE 3
extern  enum clnt_stat get_value_1();
extern  bool_t get_value_1_svc();
#define MODIFY_VALUE 4
extern  enum clnt_stat modify_value_1();
extern  bool_t modify_value_1_svc();
#define DELETE_KEY 5
extern  enum clnt_stat delete_key_1();
extern  bool_t delete_key_1_svc();
#define EXIST 6
extern  enum clnt_stat exist_1();
extern  bool_t exist_1_svc();
extern int clave_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_tuple_t (XDR *, tuple_t*);
extern  bool_t xdr_returnGetValue (XDR *, returnGetValue*);

#else /* K&R C */
extern bool_t xdr_tuple_t ();
extern bool_t xdr_returnGetValue ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_CLAVES_H_RPCGEN */
