/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc_claves.h"

bool_t
xdr_tuple_t (XDR *xdrs, tuple_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, 256))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->N_value2))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->V_value2.V_value2_val, (u_int *) &objp->V_value2.V_value2_len, 32,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_returnGetValue (XDR *xdrs, returnGetValue *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->result))
		 return FALSE;
	 if (!xdr_tuple_t (xdrs, &objp->tuple_result))
		 return FALSE;
	return TRUE;
}
