/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "vector.h"

bool_t
xdr_t_vector (XDR *xdrs, t_vector *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->t_vector_val, (u_int *) &objp->t_vector_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}
