/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VECTOR_H_RPCGEN
#define _VECTOR_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


typedef struct {
	u_int t_vector_len;
	int *t_vector_val;
} t_vector;

#define VECTOR 99
#define VECTORVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define sumar 1
extern  enum clnt_stat sumar_1(t_vector , int *, CLIENT *);
extern  bool_t sumar_1_svc(t_vector , int *, struct svc_req *);
extern int vector_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define sumar 1
extern  enum clnt_stat sumar_1();
extern  bool_t sumar_1_svc();
extern int vector_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_t_vector (XDR *, t_vector*);

#else /* K&R C */
extern bool_t xdr_t_vector ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_VECTOR_H_RPCGEN */
