/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "rpc_logger.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
log_1(char *message, void *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, LOG,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &message,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}
