/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LISTA_H_RPCGEN
#define _LISTA_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct lista {
	int x;
	struct lista *next;
};
typedef struct lista lista;

typedef lista *t_lista;

#define LISTA 99
#define LISTAVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define sumar 1
extern  enum clnt_stat sumar_1(t_lista , int *, CLIENT *);
extern  bool_t sumar_1_svc(t_lista , int *, struct svc_req *);
extern int lista_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define sumar 1
extern  enum clnt_stat sumar_1();
extern  bool_t sumar_1_svc();
extern int lista_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_lista (XDR *, lista*);
extern  bool_t xdr_t_lista (XDR *, t_lista*);

#else /* K&R C */
extern bool_t xdr_lista ();
extern bool_t xdr_t_lista ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LISTA_H_RPCGEN */
