/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "lista.h"


void
lista_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	t_lista  sumar_1_l;

	clnt = clnt_create (host, LISTA, LISTAVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}



	struct lista n1, n2;
        sumar_1_l = &n1;
        n1.x = 5;   n1.next = &n2;
        n2.x = 3;   n2.next = NULL;


	retval_1 = sumar_1(sumar_1_l, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}

	printf("La suma es %d\n", result_1);

	clnt_destroy (clnt);
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	lista_1 (host);
exit (0);
}
