/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "lista.h"

bool_t
xdr_lista (XDR *xdrs, lista *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (lista), (xdrproc_t) xdr_lista))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_t_lista (XDR *xdrs, t_lista *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (lista), (xdrproc_t) xdr_lista))
		 return FALSE;
	return TRUE;
}
