/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "vector.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
sumar_1(t_vector v, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, sumar,
		(xdrproc_t) xdr_t_vector, (caddr_t) &v,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
