/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "string.h"


void
string_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	char vocales_1_arg1[256];
	enum clnt_stat retval_2;
	char result_2;
	char first_1_arg1[256];
	enum clnt_stat retval_3;
	char *result_3;
	int convertir_1_n;

	clnt = clnt_create (host, STRING, STRINGVER, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

	strcpy(vocales_1_arg1, "Prueba");	
	retval_1 = vocales_1(vocales_1_arg1, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	else
		printf("%s  tiene %d vocales \n", vocales_1_arg1, result_1);


	strcpy(first_1_arg1, "Prueba");	
	retval_2 = first_1(first_1_arg1, &result_2, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	else
		printf("La inicial es %c \n", result_2);


	convertir_1_n = 124;
	result_3 = (char *) malloc(256);
	retval_3 = convertir_1(convertir_1_n, &result_3, clnt);
	if (retval_3 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	else
		printf("%d es %s\n",convertir_1_n, result_3);
	free(result_3);
	



	clnt_destroy (clnt);
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	string_1 (host);
exit (0);
}
