/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "string.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
vocales_1(char *arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, vocales,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
first_1(char *arg1, char *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, first,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &arg1,
		(xdrproc_t) xdr_char, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
convertir_1(int n, char **clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, convertir,
		(xdrproc_t) xdr_int, (caddr_t) &n,
		(xdrproc_t) xdr_wrapstring, (caddr_t) clnt_res,
		TIMEOUT));
}
