/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <string.h>
#include <rpc/xdr.h>
#include "string.h"

bool_t
vocales_1_svc(char *arg1, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */
	int n = 0;
	while (*arg1 != '\0'){
                if (*arg1 == 'a' || *arg1 == 'e' || 
			*arg1 == 'i' || *arg1 == 'o' || *arg1 == 'u' )
                        n++;
                arg1++;
        }
        *result = n;


	return retval;
}

bool_t
first_1_svc(char *arg1, char *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	        *result = arg1[0];


	return retval;
}

bool_t
convertir_1_svc(int n, char **result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */


	*result = (char *) malloc(256);

	sprintf(*result, "En texto= %d", n);

	printf(".......... %s\n", *result);

	return retval;
}

int
string_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{

	printf("............................................\n");
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
