/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "suma.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
suma_1(int a, int b, int *clnt_res,  CLIENT *clnt)
{
	suma_1_argument arg;
	arg.a = a;
	arg.b = b;
	return (clnt_call (clnt, SUMA, (xdrproc_t) xdr_suma_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
resta_1(int a, int b, int *clnt_res,  CLIENT *clnt)
{
	resta_1_argument arg;
	arg.a = a;
	arg.b = b;
	return (clnt_call (clnt, RESTA, (xdrproc_t) xdr_resta_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
